---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

stages:
  - test
  - deploy_demo

env:
  global:
    secure: ljbB8yGsFDxC6J8z1jLe9ipSGubUkvcsFiqLaY/utfb6fr8PPFG8wGtztXATb8i8T1nCHbrgezsRaAIXBaUaUIYxmgEZRtSkBUgGKiEQ2ZvNlNIYZ4JS604BIROuGIHg3JOF1RMYBAqoc+xwy5PYP47KSTSPeWIfC+OhzJeur1NYUcxiCNHHMBboqrJKoj8ExVkI9kKjZUWVXhzVZ0PU5z263wD6M4FSXJxNZJsArGr83OZHllApt8QiSg+GRbAPICP59vxlQR/yRMp8PCh3CLId7NHPIbikoFoLQ6e7BQ1+5V3osGZ9oXhLJDFO+x2Gd4BrC5Vx1cvypBqg/pzbcBDAN42tjMG0lHoi2r0/FmIXPGis5kxLF/6GqTQ8xX0x2zpS7e+AVa/tMqEtAR1qk83aGGKW7aj70BbgOr+u3H1UfJ/l8CT7kcxssFSqWBVg/92crpaupqBwuk6xp+HonZYqlivelwtG+PSDTzFbAU1qza/lu+DKMHDm5sEVCjNUfrOuCubhOt4+vqvtR17mZIca/pBSVEi9WbMcRrBWgpiHx8/b5w4GAC3AguGTOKaOTEtilbsi37BM+nf7FhKtUXK8/zg9b6i5zTjFAQ9e/foGBJeCW0LV1JbL2zwdesok+UCFekX19HIfJ7i6OHySBG9KtVtuyJB/aDzoIY0aggg=
  matrix:
    - SCRIPT=test:all
    - SCRIPT=test:fastboot
    - SCRIPT=test:node

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install --no-lockfile

script: npm run $SCRIPT

deploy:
  provider: npm
  email: info@simplabs.com
  api_key:
    secure: dKp+BvoSv8vUN90m9fH2oOK/sQ12K5B5BrWjfn1m2evpc9TFZGHLlqSsAw4Cq9JmK7SgRKsuh4O2k1CO8QAXW6mMjD/NSGJfBz+grdXE20kqOlIPvj9sQ9PVpqgmTA5bZvhbhXn8ybKqgTabZZrED9eMkrSqMN5xU1oW414DNwQ=
  on:
    tags: true
    repo: simplabs/ember-simple-auth

jobs:
  include:
    - stage: deploy_demo
      script: npm i -g now-pipeline; cd server && now-pipeline-prune && now-pipeline --alias ember-simple-auth-server.now.sh; now-pipeline-prune && now-pipeline --alias ember-simple-auth.now.sh

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
